### ISSUE TITLE
[ToDo] Cloud, Web-API 関連

### ISSUE THREAD

**Issue by Yagami360** [Yagami360/MachineLearning_PreProcessing_Exercises#2]
## トピック
- Could Function
    - Could Function でリクエストを送信＆受信する
    - サーバー上の docker コンテナでの処理を Could Function で行うようにする
    - Cloud Run
    - ロードバランサー
        - インスタンスグループを利用したロードバランサーの導入、自動スケーリング
    - Kubernetes/ GKE [Google Kubernetes Engine]
        - GKE : Googleが提供する Kubernetes
        - Kubernetes は多数のコンポーネントで構成されており、そのまま運用するのは
    - FireBase
        - xxx

## ToDo（Could Function）
- [ ] GCP インスタンス作成（GPU）
- [ ] gcloud のインストール
- [ ] Could Function のサンプルコードが動くようにする
- [ ] 自作の API サーバーが 非docker で動くようにする（Graphonomyサーバー等）
- [ ] 自作の API サーバーが docker で動くようにする
- [ ] 自作の API サーバーを Could Function に自動デプロイ
- [ ] リクエスト処理を Could Function にデプロイし、Could Function からサーバー上の API が動作し、レスポンスを返すようにする
    - Could Function 用にコードを修正する必要あり
- [ ] レスポンス処理も Could Function にデプロイし、全ての動作が Could Function 上で動作するようにする（サーバレス動作）

## ToDo（Could Run）
- [ ] Clould Run の理解
- [ ] Clould Run のサンプルコードが動くようにする
- [ ] 自作の API サーバーが Could Run に自動デプロイで動くようにする
	
## ToDo（ロードバランサー）
- [ ] インスタンスグループを利用したロードバランサーの導入
- [ ] xxx

## ToDo（GKE）
- [ ] GKE の理解

## ToDo（FireBase）
- [ ] FireBase の理解
